feat(button): add icon only buttons
nl-design-system/denhaag pull request #1078
Opened 2022-08-30 13:47 UTC by robbieatacato

### Solve:

- new button icon only missing

### Purpose:

- add icon only buttons, bem + css

closes

2022-08-30 14:27 UTC, paulAcato requested changes

2022-08-30 14:27 UTC, paulAcato commented on components/Button/src/stories/bem.stories.mdx
> +      <button class="denhaag-button denhaag-button--end-icon denhaag-button--icon-only denhaag-button--hover">
No need for `denhaag-button--end-icon`, should be handled by the `--icon-only` modifier or default `denhaag-button` class.

2022-08-30 14:27 UTC, paulAcato commented on components/Button/src/stories/bem.stories.mdx
> +      <button class="denhaag-button denhaag-button--end-icon denhaag-button--icon-only denhaag-button--focus">
No need for `denhaag-button--end-icon`, should be handled by the `--icon-only` modifier or default `denhaag-button` class.

2022-08-30 14:27 UTC, paulAcato commented on components/Button/src/index.scss
> +  padding-block-start: var(--denhaag-button-medium-size-padding-block);
This paddings are set on the default `denhaag-button` selector on line #13 til #16. No need for duplicate CSS

2022-08-30 14:27 UTC, paulAcato commented on components/Button/src/stories/bem.stories.mdx
> +        <span class="denhaag-button__icon">
This element doesn't have any readable text for screenreaders, therefor the `sr-only` element or `aria-label` attribute must be applied. So the Screenreader mentions what this does.

2022-08-30 14:27 UTC, paulAcato commented on components/Button/src/stories/bem.stories.mdx
> +      <button class="denhaag-button denhaag-button--secondary-action denhaag-button--end-icon denhaag-button--icon-only">
This element doesn't have any readable text for screenreaders, therefor the `sr-only` element or `aria-label` attribute must be applied. So the Screenreader mentions what this does.

2022-08-30 14:27 UTC, paulAcato commented on components/Button/src/stories/bem.stories.mdx
> +      <button class="denhaag-button denhaag-button--end-icon denhaag-button--icon-only">
This element doesn't have any readable text for screenreaders, therefor the `sr-only` element or `aria-label` attribute must be applied. So the Screenreader mentions what this does.

2022-08-30 14:27 UTC, paulAcato commented on components/Button/src/stories/bem.stories.mdx
> +      <button class="denhaag-button denhaag-button--end-icon denhaag-button--icon-only denhaag-button--hover">
This element doesn't have any readable text for screenreaders, therefor the `sr-only` element or `aria-label` attribute must be applied. So the Screenreader mentions what this does.

2022-08-30 14:27 UTC, paulAcato commented on components/Button/src/stories/bem.stories.mdx
> +      <button class="denhaag-button denhaag-button--secondary-action denhaag-button--end-icon denhaag-button--icon-only denhaag-button--hover">
This element doesn't have any readable text for screenreaders, therefor the `sr-only` element or `aria-label` attribute must be applied. So the Screenreader mentions what this does.

2022-08-30 14:27 UTC, paulAcato commented on components/Button/src/stories/bem.stories.mdx
> +      <button class="denhaag-button denhaag-button--end-icon denhaag-button--icon-only denhaag-button--hover">
This element doesn't have any readable text for screenreaders, therefor the `sr-only` element or `aria-label` attribute must be applied. So the Screenreader mentions what this does.

2022-08-30 14:27 UTC, paulAcato commented on components/Button/src/stories/bem.stories.mdx
> +      <button class="denhaag-button denhaag-button--end-icon denhaag-button--icon-only denhaag-button--hover">
This element doesn't have any readable text for screenreaders, therefor the `sr-only` element or `aria-label` attribute must be applied. So the Screenreader mentions what this does.

2022-08-30 14:27 UTC, paulAcato commented on components/Button/src/stories/bem.stories.mdx
> +        class="denhaag-button denhaag-button--secondary-action denhaag-button--end-icon denhaag-button--icon-only denhaag-button--disabled"
This element doesn't have any readable text for screenreaders, therefor the `sr-only` element or `aria-label` attribute must be applied. So the Screenreader mentions what this does.

2022-08-30 14:27 UTC, paulAcato commented on components/Button/src/stories/bem.stories.mdx
> +        class="denhaag-button denhaag-button--end-icon denhaag-button--icon-only denhaag-button--disabled"
This element doesn't have any readable text for screenreaders, therefor the `sr-only` element or `aria-label` attribute must be applied. So the Screenreader mentions what this does.

2022-08-30 14:27 UTC, paulAcato commented on components/Button/src/stories/bem.stories.mdx
> +        class="denhaag-button denhaag-button--end-icon denhaag-button--icon-only denhaag-button--disabled"
This element doesn't have any readable text for screenreaders, therefor the `sr-only` element or `aria-label` attribute must be applied. So the Screenreader mentions what this does.

2022-08-30 14:27 UTC, paulAcato commented on components/Button/src/stories/bem.stories.mdx
> +      <button class="denhaag-button denhaag-button--end-icon denhaag-button--icon-only denhaag-button--focus">
This element doesn't have any readable text for screenreaders, therefor the `sr-only` element or `aria-label` attribute must be applied. So the Screenreader mentions what this does.

2022-08-30 14:27 UTC, paulAcato commented on components/Button/src/stories/bem.stories.mdx
> +      <button class="denhaag-button denhaag-button--secondary-action denhaag-button--end-icon denhaag-button--icon-only denhaag-button--focus">
This element doesn't have any readable text for screenreaders, therefor the `sr-only` element or `aria-label` attribute must be applied. So the Screenreader mentions what this does.

2022-08-30 14:27 UTC, paulAcato commented on components/Button/src/stories/bem.stories.mdx
> +      <button class="denhaag-button denhaag-button--end-icon denhaag-button--icon-only denhaag-button--focus">
This element doesn't have any readable text for screenreaders, therefor the `sr-only` element or `aria-label` attribute must be applied. So the Screenreader mentions what this does.

2022-08-30 16:19 UTC, robbieatacato commented on components/Button/src/stories/bem.stories.mdx
> +      <button class="denhaag-button denhaag-button--end-icon denhaag-button--icon-only">
scherp opgemerkt

2022-08-31 07:16 UTC, paulAcato approved these changes

2022-08-31 07:31 UTC, merged