Feature/gdh 913 radio animation
nl-design-system/denhaag pull request #1150
Opened 2022-11-23 09:58 UTC by paulAcato

[animation-radios.webm](https://user-images.githubusercontent.com/94894596/203518124-4e640f76-b347-4f99-9003-723d2bc637d1.webm)

2022-11-23 11:01 UTC, robbieatacato commented
> 

@paulAcato de screen capture werkt niet bij mij

2022-11-23 14:00 UTC, robbieatacato requested changes

2022-11-23 14:00 UTC, robbieatacato commented on components/Radio/src/stories/bem.stories.mdx
>        <label class="denhaag-form-control-label">
{() => (
Volgens mij mag de react uit de bem, hiervoor is een aparte react.stories.mdx file, inlcusief de comment {/* eslint-disable jsx-a11y/label-has-associated-control */}
jsx = react namelijk

2022-11-23 14:00 UTC, robbieatacato commented on components/Radio/src/stories/bem.stories.mdx
>      {() => (
Volgens mij mag de react uit de bem, hiervoor is een aparte react.stories.mdx file

2022-11-23 14:00 UTC, robbieatacato commented on components/Radio/src/stories/bem.stories.mdx
>        <label class="denhaag-form-control-label denhaag-form-control-label--disabled">
{() => ( 
Volgens mij mag de react uit de bem, hiervoor is een aparte react.stories.mdx file

2022-11-23 14:00 UTC, robbieatacato commented on components/Radio/src/stories/bem.stories.mdx
>        <label class="denhaag-form-control-label">
{() => (
Volgens mij mag de react uit de bem, hiervoor is een aparte react.stories.mdx file

2022-11-24 08:51 UTC, paulAcato commented on proprietary/Components/src/denhaag/radio.tokens.json
> +          "size": { "value": "8px" },
Wordt heel specifiek 8px genoemd, dus dan houd ik dat aan.

2022-11-24 10:56 UTC, paulAcato commented
Can't remove the `jsx-a11y/label-has-associated-control` enable/disable.  Therefore I only deleted the `{() => (` part.

`/Projecten/nl-design-system/components/Radio/src/stories/bem.stories.mdx
   31:5  error  A form label must be associated with a control  jsx-a11y/label-has-associated-control
   72:5  error  A form label must be associated with a control  jsx-a11y/label-has-associated-control
   99:5  error  A form label must be associated with a control  jsx-a11y/label-has-associated-control
  127:5  error  A form label must be associated with a control  jsx-a11y/label-has-associated-control
  150:9  error  A form label must be associated with a control  jsx-a11y/label-has-associated-control
  161:9  error  A form label must be associated with a control  jsx-a11y/label-has-associated-control
  172:9  error  A form label must be associated with a control  jsx-a11y/label-has-associated-control
  200:9  error  A form label must be associated with a control  jsx-a11y/label-has-associated-control
  217:9  error  A form label must be associated with a control  jsx-a11y/label-has-associated-control
  234:9  error  A form label must be associated with a control  jsx-a11y/label-has-associated-control
  265:5  error  A form label must be associated with a control  jsx-a11y/label-has-associated-control
`

2022-11-24 10:57 UTC, paulAcato commented on components/Radio/src/stories/bem.stories.mdx
> +  {/* eslint-enable jsx-a11y/label-has-associated-control */}
Read the comment: https://github.com/nl-design-system/denhaag/pull/1150#issuecomment-1326285198

2022-11-24 11:28 UTC, robbieatacato approved these changes

2022-11-24 11:30 UTC, merged