Fix Link component override
nl-design-system/denhaag pull request #1441
Opened 2024-01-30 14:30 UTC by YourivHDenHaag

2024-01-30 15:14 UTC, Yolijn requested changes
Ziet er super goed uit! Alleen die lock-file moet er denk ik niet bij?

2024-01-30 16:16 UTC, Robbert commented
For reference, this is our approach for similar golas in a project for gemeente Utrecht:
https://github.com/frameless/strapi/blob/main/packages/ui/src/components/AdvancedLink/index.tsx

2024-01-31 12:37 UTC, YourivHDenHaag commented
> Ziet er super goed uit! Alleen die lock-file moet er denk ik niet bij?

@Yolijn Geen idee wat daar precies gebeurd is. Wanneer ik pnpm install doe krijg ik dezelfde lock file.

2024-01-31 12:40 UTC, Borai approved these changes

2024-01-31 13:20 UTC, merged