Patch round 2024-05
nl-design-system/denhaag pull request #1535
Opened 2024-05-29 09:12 UTC by matijs

- husky 9 configuration
  - Clean up hook scripts
  - Use pnpm instead of npx in hook scripts
  - Replace package.json#postinstall with package.json#prepare

- install patch updates
- install minor updates
- install major updates, prevent updating the following deps:
  - eslint, eslint-plugin-json because the ecosystem is not ready yet
  - storybook, storybook/* because it is too much effort right now
  - prettier because prettier 3 is async

- Rename to .cjs for clarity
- Make sure that lint-staged picks up .mjs and .cjs files
- Make sure that eslint picks up .cjs files

2024-05-30 06:50 UTC, Robbert commented
"47 tests fail to render"

@matijs er gaat nog iets mis: https://62d1558ac36c853a5aaad43f-qhvffahbuo.chromatic.com/?path=/story/templates-login--login

Werkt wel in `main`: https://nl-design-system.github.io/denhaag/?path=/story/templates-login--login

2024-05-30 06:50 UTC, Robbert requested changes

2024-05-30 06:50 UTC, Robbert commented on .husky/commit-msg
> +pnpm commitlint --edit "$1"
moet dit `pnpm exec` zijn?

2024-05-30 06:50 UTC, Robbert commented on .husky/pre-commit
> +pnpm lint-staged
moet dit `pnpm exec` zijn?

2024-05-30 06:50 UTC, Robbert commented on .husky/pre-commit
> +pnpm lint-staged
```suggestion
pnpm exec lint-staged
```

2024-05-30 06:50 UTC, Robbert commented on .husky/commit-msg
> +pnpm commitlint --edit "$1"
```suggestion
pnpm exec commitlint --edit "$1"
```

2024-05-30 11:57 UTC, Borai reviewed
LGTM 🚀

2024-05-31 07:51 UTC, matijs commented
Closing in favour of #1537

2024-05-31 07:51 UTC, closed without merging