style(dynamics content): reduce tokens
nl-design-system/denhaag pull request #1604
Opened 2024-11-18 14:23 UTC by marcoderover

2024-11-18 15:10 UTC, paulAcato commented on proprietary/Components/src/denhaag/dynamic-content.tokens.json
>          "opacity": {
Deze zou ook nog weg kunnen ;-)

2024-11-18 15:11 UTC, paulAcato commented on proprietary/Components/src/denhaag/dynamic-content.tokens.json
>          "gap": {
Deze zou ook nog weg kunnen ;-)

2024-11-21 12:20 UTC, paulAcato requested changes

2024-11-21 12:20 UTC, paulAcato commented on components/DynamicContent/src/index.scss
> +  opacity: var(--denhaag-dynamic-content-icon-opacit, 0%);
Typo

2024-11-21 13:49 UTC, marcoderover commented on proprietary/Components/src/denhaag/dynamic-content.tokens.json
>          "gap": {
Verwijderd!.

2024-11-22 08:25 UTC, merged