style(event date): reduce tokens
nl-design-system/denhaag pull request #1606
Opened 2024-11-18 15:45 UTC by marcoderover

2024-11-18 15:55 UTC, paulAcato approved these changes

2024-11-18 15:59 UTC, paulAcato requested changes

2024-11-18 15:59 UTC, paulAcato commented on components/EventDate/src/index.scss
> +  margin-inline-end: var(--denhaag-event-date-icon-margin-inline-end, 0.5rem);
Niet `var(--denhaag-space-xs)` ?

2024-11-19 09:15 UTC, marcoderover commented
@paulAcato ik heb hier ook een button-border-width hersteld ivm de build error.

2024-11-19 12:15 UTC, paulAcato approved these changes

2024-11-19 12:15 UTC, merged