[DRAFT] Add rollup bundlder
nl-design-system/denhaag pull request #241
Opened 2021-06-10 07:23 UTC by bddjong

2021-06-11 21:32 UTC, mjcarsjens commented
Hmm, looks like a solid first setup but there seem to still be some quirks with it. Have been doing some "light" reading into rollup but not quite sure yet how we could improve this. One quick observation for now: the `rollup-plugin-typescript` dependency/package is no longer maintained, and has been replaced by `@rollup/plugin-typescript`. ([source](https://github.com/rollup/rollup-plugin-typescript))

2021-06-23 08:06 UTC, joostvanviegen commented on src/components/AppBar/package.json
> -        "@gemeente-denhaag/typography": "*"
Wat is de reden dat typography weg is?

2021-06-23 08:11 UTC, joostvanviegen commented on src/components/Card/tsconfig.json
> +    "composite": true,
Wat is de reden dat composite bij de rest weg is, maar hier niet?

2021-06-23 08:44 UTC, joostvanviegen approved these changes
It looks okay, have made some comments about questions I have regarding some changes.

2021-06-30 06:23 UTC, bddjong commented on src/components/AppBar/package.json
> -        "@gemeente-denhaag/typography": "*"
It's unused

2021-06-30 06:30 UTC, bddjong commented
@GewoonMaarten my IDE complains about the  added svgr rollup plugin not being a function
![image](https://user-images.githubusercontent.com/24610692/123912551-7874ec00-d97d-11eb-9ede-af7f262249ec.png)

Does this happen for you as well?

2021-06-30 07:23 UTC, GewoonMaarten commented
> @GewoonMaarten my IDE complains about the added svgr rollup plugin not being a function
> ![image](https://user-images.githubusercontent.com/24610692/123912551-7874ec00-d97d-11eb-9ede-af7f262249ec.png)
> 
> Does this happen for you as well?

@bddjong no, mine doesn't give any warnings. But it does work, right?

2021-06-30 07:30 UTC, bddjong commented
> > @GewoonMaarten my IDE complains about the added svgr rollup plugin not being a function
> > ![image](https://user-images.githubusercontent.com/24610692/123912551-7874ec00-d97d-11eb-9ede-af7f262249ec.png)
> > Does this happen for you as well?
> 
> @bddjong no, mine doesn't give any warnings. But it does work, right?

Yeapp it does

2021-06-30 11:35 UTC, GewoonMaarten commented
Sorry for the mess up 😬

2021-07-03 07:37 UTC, bddjong commented
Just tested it and ran into no issues (finally). Only thing is that we still have a microsoft copyright notice in some of our bundles. I'm not sure if that's rollup being weird with typescript.

2021-07-03 08:19 UTC, GewoonMaarten submitted a review, later dismissed

2021-07-03 12:09 UTC, DanielvanVliet requested changes
It seems that Proprietary still overwrites index.js, and thus I cant import css from it in a react app.

2021-07-03 12:13 UTC, bddjong commented
> It seems that Proprietary still overwrites index.js, and thus I cant import css from it in a react app.

You should be able to import it from the dist for now

2021-07-03 13:00 UTC, DanielvanVliet requested changes
The List styling is not loaded entirely, some css rules are missing. Strange behaviour that could be caused by PostCSS.

2021-07-06 10:51 UTC, bddjong commented
Tested with verdaccio and confirmed to be working in an external javascript react app. I suggest we merge this and open issues for remaining optimizations so that we can publish the new components.

2021-07-06 11:10 UTC, GewoonMaarten approved these changes

2021-07-07 08:02 UTC, DanielvanVliet commented on src/components/FormControlLabel/src/index.tsx
> +import { FormControlLabel as MaterialFormControlLabel } from '@material-ui/core/';
```suggestion
import { FormControlLabel as MaterialFormControlLabel } from '@material-ui/core';
```

2021-07-07 08:09 UTC, DanielvanVliet approved these changes

2021-07-07 10:51 UTC, merged