Feature/596 html modal
nl-design-system/denhaag pull request #601
Opened 2021-12-09 14:04 UTC by paulAcato

Modal HTML, CSS and JS parts.

![Screenshot 2021-12-09 at 15 03 08](https://user-images.githubusercontent.com/94894596/145410705-7901a506-e6eb-4259-95bc-79c05801aa0d.png)

closes #596

2021-12-20 12:26 UTC, bddjong requested changes

2021-12-20 13:11 UTC, paulAcato commented on components/Modal/src/modal.css
> +  padding-block-end: var(--denhaag-modal-icon-padding-block, var(--denhaag-modal-padding));
@bddjong , I used the button as example,

When I check the button component I saw the following;
`padding-block-end: var(--denhaag-button-medium-size-padding-block, var(--denhaag-button-padding-block));
  padding-block-start: var(--denhaag-button-medium-size-padding-block, var(--denhaag-button-padding-block));
  padding-inline-end: var(--denhaag-button-medium-size-padding-inline, var(--denhaag-button-padding-inline));
  padding-inline-start: var(--denhaag-button-medium-size-padding-inline, var(--denhaag-button-padding-inline));`
  
 Therefor I applied the same logic with the `var(--denhaag-modal-padding);` as fallback. But i'll change it, no problem

2021-12-20 13:12 UTC, paulAcato commented on components/Modal/src/modal.css
> +  font-size: var(--denhaag-modal-icon-size, var(--denhaag-modal-padding));
I missed this, should be inherit as fallback.

2021-12-22 10:41 UTC, bddjong commented
Is it correct that the opening / closing javascript doesn't work in storybook?

2021-12-22 15:33 UTC, paulAcato commented
> Is it correct that the opening / closing javascript doesn't work in storybook?

@bddjong , they should work. At my place they're working? See the attached video

https://user-images.githubusercontent.com/94894596/147116513-1059cd9d-46fc-426b-9eb7-27dae474ade5.mp4

2021-12-23 09:19 UTC, bddjong commented
> > Is it correct that the opening / closing javascript doesn't work in storybook?
> 
> @bddjong , they should work. At my place they're working? See the attached video

I tested the storybook stories on both Chrome and Firefox. In the case of Firefox, I was unable to even press that buttons (@mjcarsjens can you test this branch to confirm that?). In Chrome, pressing the buttons didn't do anything.

2021-12-23 11:01 UTC, bddjong commented
Just tested in Safari. Safari works fine.

2021-12-23 12:23 UTC, paulAcato commented
> Just tested in Safari. Safari works fine the first time, but not after switching between Canvas and Docs in storybook.

I just edited the pointer-event, where FireFox broke on.

2021-12-28 10:53 UTC, bddjong approved these changes

2022-01-17 13:40 UTC, bddjong requested changes
Only noticed one more issue, looks good otherwise

2022-01-17 15:23 UTC, robbieatacato commented on components/Modal/src/index.tsx
> +import './stories.js';
fixed it, see commits

2022-01-19 08:18 UTC, bddjong approved these changes

2022-01-24 14:57 UTC, merged