Feature/609 cta link
nl-design-system/denhaag pull request #615
Opened 2021-12-16 09:30 UTC by paulAcato

Call to action Link variation;
- Default link;
- Video variant;
- Hovered;
- Focused;
- Grouped;
- Long;

closes #609

2022-01-14 10:35 UTC, bddjong requested changes
Few small comments

2022-01-14 10:35 UTC, bddjong commented on components/CtaLink/tsconfig.json
> +    }
Baseprops are unused

2022-01-14 10:35 UTC, bddjong commented on proprietary/Components/src/denhaag/cta-link.tokens.json
> +        "value": "{denhaag.color.grey.2.value}"
`.value` can be omitted with the latest version of style dictionary.

2022-01-17 14:55 UTC, robbieatacato commented
added changes requested above

2022-01-25 16:13 UTC, merged