Feature/612 cta event
nl-design-system/denhaag pull request #616
Opened 2021-12-17 09:00 UTC by paulAcato

Added HTML and css story for the CTA Event element, used the CTA Link (previously CTA Icon) as base, since they're quite equal. 

closes #612 #615 #609

2022-01-14 10:39 UTC, bddjong requested changes

2022-01-14 10:39 UTC, bddjong commented on components/CtaEvent/tsconfig.json
> +    }
Unused reference

2022-01-14 10:39 UTC, bddjong commented on proprietary/Components/src/denhaag/cta-event.tokens.json
> +        "value": "{denhaag.color.grey.2.value}"
`.value` can be removed

2022-01-17 15:49 UTC, robbieatacato commented
@bddjong made the changes requested above + resolved merge conflicts

2022-01-25 18:18 UTC, merged