feat(blockquote): add story, css, tokens
nl-design-system/denhaag pull request #699
Opened 2022-01-13 13:02 UTC by robbieatacato

## Solves
https://github.com/nl-design-system/denhaag/issues/610

## Purpose
Blockquote:
- html
- css
- tokens

##closes https://github.com/nl-design-system/denhaag/issues/610

2022-01-26 13:20 UTC, robbieatacato commented
@bddjong also merge conflict with main solved.

2022-01-27 09:15 UTC, bddjong requested changes

2022-01-27 09:15 UTC, bddjong commented on components/Blockquote/src/index.css
> +    var(--denhaag-blockquote-border-color, #d5e7d4);
We don't want fallbacks with proprietary colors. No fallback is a valid option.

2022-01-27 09:15 UTC, bddjong commented on components/Blockquote/src/index.css
> +  color: var(--denhaag-blockquote-paragraph-color, #1d6b34);
Dito about color fallbacks

2022-01-27 09:15 UTC, bddjong commented on components/Blockquote/src/index.css
> +  font-size: var(--denhaag-blockquote-attribution-font-size, 0.625rem);
I've added a comment in figma about this font-size. I think 10px is not user friendly from an accessibility perspective. https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn?node-id=8123:22417#145088346

2022-01-27 09:15 UTC, bddjong commented on components/Blockquote/tsconfig.json
> +    }
Unused reference

2022-01-27 14:00 UTC, merged