Feature/checkboxes and radio
nl-design-system/denhaag pull request #860
Opened 2022-03-29 09:42 UTC by mjcarsjens

Implementation for Radio Buttons and Checkboxes, reworked FormControlLabel and FormField to work with these.

**Closing issues**

- `closes #820`
- `closes #821`

2022-03-30 21:54 UTC, bddjong requested changes

2022-03-30 21:54 UTC, bddjong commented on components/Checkbox/src/stories/react.stories.mdx
> +  <Story name="Default" args={{}}>
A few of the checkbox stories show a prop error in storybook

2022-03-30 21:54 UTC, bddjong commented on components/Checkbox/src/stories/bem.stories.mdx
> +  title="CSS/Input/Checkbox"
Can we have BEM stories for checkbox and radio groups?

2022-03-31 07:55 UTC, bddjong commented
Keyboard navigation on the radio button form field is broken on chrome. It’s not selecting the radio button which has a hover

2022-03-31 12:20 UTC, mjcarsjens commented on components/Checkbox/src/stories/react.stories.mdx
> +  <Story name="Default" args={{}}>
Works on my machine ¯\_(ツ)_/¯

2022-04-01 10:49 UTC, bddjong approved these changes

2022-04-01 10:49 UTC, bddjong commented on components/Checkbox/src/index.scss
> +  border-radius: var(--utrecht-custom-checkbox-border-radius);
I think the `utrecht-form-input` border is identical. Maybe it's useful to add those tokens as fallback values so other organisations won't have to define as many tokens.

2022-04-01 10:49 UTC, bddjong commented on components/Checkbox/src/index.scss
> +  border-color: var(--utrecht-custom-checkbox-invalid-border-color);
Same here and for other styles if they already exist as `form-input` tokens. (Mind that we also have a few `denhaag-input` tokens that could be used as fallbacks)

2022-04-01 11:30 UTC, merged